package com.bizsage.api.messages;

import static org.assertj.core.api.Assertions.assertThat;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ConversationSchemaMigrationTest {
  @Test
  void upgradesLegacyConversationTablesForMessageStreaming() {
    JdbcDataSource dataSource = new JdbcDataSource();
    dataSource.setURL("jdbc:h2:mem:conversation_schema_migration;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");

    JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
    jdbcTemplate.execute("drop table if exists messages");
    jdbcTemplate.execute("drop table if exists conversation_summaries");
    jdbcTemplate.execute("""
        create table messages (
          id bigint generated by default as identity primary key,
          conversation_id bigint not null,
          sender varchar(32) not null,
          content clob not null,
          create_time timestamp not null default current_timestamp
        )
        """);

    ConversationSchemaMigration migration = new ConversationSchemaMigration(jdbcTemplate);
    migration.migrate();

    ConversationMessageStore messageStore = new ConversationMessageStore(jdbcTemplate);
    long messageId = messageStore.append(
        42L,
        "USER",
        "QUESTION",
        "门店最近现金流偏紧",
        "[\"seed://cashflow\"]",
        "HIGH",
        "RECENT",
        "PASSED",
        "cn-default",
        "general");

    ConversationSummaryStore summaryStore = new ConversationSummaryStore(jdbcTemplate);
    ConversationSummary summary = summaryStore.save(42L, "总结", messageId, messageId);

    assertThat(messageStore.activeMessages(42L))
        .singleElement()
        .extracting(ConversationMessage::messageType, ConversationMessage::content)
        .containsExactly("QUESTION", "门店最近现金流偏紧");
    assertThat(summaryStore.latestActive(42L)).contains(summary);
  }
}
