CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  phone_encrypted VARCHAR(255),
  identity_encrypted VARCHAR(255),
  membership_level VARCHAR(32) NOT NULL DEFAULT 'FREE',
  consultation_preferences VARCHAR(255) NOT NULL DEFAULT '',
  preferred_locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  source_id VARCHAR(64) NOT NULL DEFAULT 'system',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  owner_username VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL DEFAULT 'user',
  agent_mode VARCHAR(32) NOT NULL DEFAULT 'DIAGNOSIS',
  workflow_stage VARCHAR(32) NOT NULL DEFAULT 'INTRO',
  profile_completeness DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  primary_issue_tags CLOB,
  recommended_question_ids CLOB,
  closed_by VARCHAR(64),
  closed_reason VARCHAR(255),
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender VARCHAR(32) NOT NULL,
  message_type VARCHAR(32) NOT NULL DEFAULT 'CHAT',
  content CLOB NOT NULL,
  sources_json CLOB,
  confidence VARCHAR(16),
  timeliness VARCHAR(255),
  self_check_status VARCHAR(32),
  is_active_context BOOLEAN NOT NULL DEFAULT TRUE,
  summary_group_id BIGINT,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  source_id VARCHAR(64) NOT NULL DEFAULT 'conversation',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversation_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  summary_text CLOB NOT NULL,
  covered_message_start_id BIGINT NOT NULL,
  covered_message_end_id BIGINT NOT NULL,
  summary_version INT NOT NULL DEFAULT 1,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  source_id VARCHAR(64) NOT NULL DEFAULT 'summary',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_memory_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  memory_category VARCHAR(32) NOT NULL,
  memory_key VARCHAR(64) NOT NULL,
  memory_value CLOB NOT NULL,
  value_type VARCHAR(16) NOT NULL DEFAULT 'STRING',
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8000,
  source_conversation_id BIGINT,
  source_message_id BIGINT,
  last_used_at TIMESTAMP,
  expires_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_memory_profiles_natural UNIQUE (user_id, memory_category, memory_key, status)
);

CREATE TABLE user_memory_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_memory_profile_id BIGINT,
  user_id BIGINT NOT NULL,
  memory_text CLOB NOT NULL,
  qdrant_point_id VARCHAR(128),
  embedding_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  source_conversation_id BIGINT,
  source_message_id BIGINT,
  last_synced_at TIMESTAMP,
  expires_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  source_url VARCHAR(1024),
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8500,
  link_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL DEFAULT 0.8500,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE question_pools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  industry_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  agent_mode VARCHAR(32) NOT NULL,
  question_key VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  question_text VARCHAR(512) NOT NULL,
  top_level_score DECIMAL(8,4) NOT NULL DEFAULT 0.5000,
  usage_count BIGINT NOT NULL DEFAULT 0,
  rating_avg DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  rating_count BIGINT NOT NULL DEFAULT 0,
  last_used_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
  source_type VARCHAR(32) NOT NULL DEFAULT 'seed',
  source_ref VARCHAR(128) NOT NULL DEFAULT '',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_question_pools_scope UNIQUE (industry_id, region_id, agent_mode, question_key)
);

INSERT INTO users (username, password_hash, role, phone_encrypted, identity_encrypted, membership_level, consultation_preferences, preferred_locale, region_id, industry_id)
VALUES
  ('user', 'password', 'USER', '13712345678', '110101199003071236', 'FREE', 'cashflow', 'zh-CN', 'cn-default', 'general'),
  ('seed_paid', 'password', 'USER', '13612345678', '110101199003071237', 'SEED_PAID', 'cashflow,inventory', 'zh-CN', 'cn-default', 'general'),
  ('internal_user', 'password', 'INTERNAL', '13512345678', '110101199003071238', 'INTERNAL', 'operations', 'zh-CN', 'cn-default', 'general');

INSERT INTO knowledge_items (title, content, source_url, confidence, link_id, region_id, industry_id, source_id, weight)
VALUES
  ('Test restaurant cash-flow baseline', 'Track order value, table turnover, ingredient loss, commission ratio, rent ratio, and receivables cycle.', 'seed://v1/restaurant-cashflow', 0.9000, 'sales-payment', 'cn-default', 'general', 'seed-baseline', 1.0000),
  ('Test inventory risk baseline', 'Watch inventory turnover days, slow-moving stock ratio, and supplier payment pressure.', 'seed://v1/inventory-risk', 0.8500, 'warehouse', 'cn-default', 'general', 'seed-baseline', 0.8500);

INSERT INTO question_pools
  (industry_id, region_id, agent_mode, question_key, category, question_text, top_level_score, source_type, source_ref)
VALUES
  ('general', 'cn-default', 'LEARNING', 'raw-materials-next', 'node', 'What does your raw material cost structure and replenishment cycle look like?', 0.9200, 'seed', 'raw-materials'),
  ('general', 'cn-default', 'DIAGNOSIS', 'baseline-industry', 'profile', 'Which industry are you in, and is the business online or offline?', 0.9500, 'seed', 'diagnosis-profile'),
  ('general', 'cn-default', 'DIAGNOSIS', 'baseline-scale', 'profile', 'Roughly how many stores, warehouses, or team members are involved?', 0.9300, 'seed', 'diagnosis-profile');
