CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  phone_encrypted VARCHAR(255),
  identity_encrypted VARCHAR(255),
  membership_level VARCHAR(32) NOT NULL DEFAULT 'FREE',
  consultation_preferences VARCHAR(255) NOT NULL DEFAULT '',
  preferred_locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  source_id VARCHAR(64) NOT NULL DEFAULT 'system',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  owner_username VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL DEFAULT 'user',
  agent_mode VARCHAR(32) NOT NULL DEFAULT 'DIAGNOSIS',
  workflow_stage VARCHAR(32) NOT NULL DEFAULT 'INTRO',
  profile_completeness DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  primary_issue_tags CLOB,
  recommended_question_ids CLOB,
  closed_by VARCHAR(64),
  closed_reason VARCHAR(255),
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender VARCHAR(32) NOT NULL,
  message_type VARCHAR(32) NOT NULL DEFAULT 'CHAT',
  content CLOB NOT NULL,
  sources_json CLOB,
  confidence VARCHAR(16),
  timeliness VARCHAR(255),
  self_check_status VARCHAR(32),
  is_active_context BOOLEAN NOT NULL DEFAULT TRUE,
  summary_group_id BIGINT,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  source_id VARCHAR(64) NOT NULL DEFAULT 'conversation',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversation_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  summary_text CLOB NOT NULL,
  covered_message_start_id BIGINT NOT NULL,
  covered_message_end_id BIGINT NOT NULL,
  summary_version INT NOT NULL DEFAULT 1,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  source_id VARCHAR(64) NOT NULL DEFAULT 'summary',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_memory_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  memory_category VARCHAR(32) NOT NULL,
  memory_key VARCHAR(64) NOT NULL,
  memory_value CLOB NOT NULL,
  value_type VARCHAR(16) NOT NULL DEFAULT 'STRING',
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8000,
  source_conversation_id BIGINT,
  source_message_id BIGINT,
  last_used_at TIMESTAMP,
  expires_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_memory_profiles_natural UNIQUE (user_id, memory_category, memory_key, status)
);

CREATE TABLE user_memory_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_memory_profile_id BIGINT,
  user_id BIGINT NOT NULL,
  memory_text CLOB NOT NULL,
  qdrant_point_id VARCHAR(128),
  embedding_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  source_conversation_id BIGINT,
  source_message_id BIGINT,
  last_synced_at TIMESTAMP,
  expires_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE intelligence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  url VARCHAR(1024),
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.6000,
  link_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL DEFAULT 0.6000,
  content_hash VARCHAR(64) NOT NULL,
  sim_hash BIGINT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paid_intelligence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  url VARCHAR(1024),
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.7500,
  entitlement VARCHAR(32) NOT NULL DEFAULT 'PAID',
  link_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL DEFAULT 0.9000,
  content_hash VARCHAR(64),
  sim_hash BIGINT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE intelligence_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_type VARCHAR(16) NOT NULL,
  scope_key VARCHAR(255) NOT NULL,
  payload_json CLOB NOT NULL,
  source_id VARCHAR(64) NOT NULL DEFAULT 'snapshot',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  retention_days INT NOT NULL DEFAULT 30,
  record_count INT NOT NULL DEFAULT 0,
  parent_snapshot_id BIGINT,
  expires_at TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE false_information_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_intelligence_id BIGINT,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  content_hash VARCHAR(64),
  url VARCHAR(1024),
  conflict_reason VARCHAR(64) NOT NULL,
  matched_rumor_keyword VARCHAR(255),
  source_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  link_id VARCHAR(64) NOT NULL,
  archived_by VARCHAR(64) NOT NULL DEFAULT 'system',
  archive_reason VARCHAR(512),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conflict_resolutions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incoming_intelligence_id BIGINT,
  existing_intelligence_id BIGINT,
  conflict_branch VARCHAR(32) NOT NULL,
  sim_hash_distance INT NOT NULL DEFAULT 0,
  incoming_weight DECIMAL(8,4) NOT NULL DEFAULT 0.6000,
  existing_weight DECIMAL(8,4) NOT NULL DEFAULT 0.6000,
  routing_action VARCHAR(64) NOT NULL,
  review_ticket_id BIGINT,
  resolved_by VARCHAR(64) NOT NULL DEFAULT 'system',
  notes VARCHAR(512),
  source_id VARCHAR(64) NOT NULL DEFAULT 'conflict-engine',
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  link_id VARCHAR(64) NOT NULL DEFAULT 'unknown',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE review_work_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type VARCHAR(64) NOT NULL,
  target_id BIGINT NOT NULL,
  reason VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  owner VARCHAR(64),
  source_id VARCHAR(64) NOT NULL DEFAULT 'review',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alert_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_level VARCHAR(16) NOT NULL,
  component VARCHAR(64) NOT NULL,
  message VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  owner VARCHAR(64),
  source_id VARCHAR(64) NOT NULL DEFAULT 'alert',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor VARCHAR(64) NOT NULL,
  action VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  result VARCHAR(32) NOT NULL,
  source_id VARCHAR(64) NOT NULL DEFAULT 'audit',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_intelligence_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intelligence_id BIGINT NOT NULL,
  review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  verdict VARCHAR(32),
  reviewer VARCHAR(64),
  reason VARCHAR(512),
  evidence_json CLOB,
  source_id VARCHAR(64) NOT NULL DEFAULT 'admin-review',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_type VARCHAR(64) NOT NULL,
  severity VARCHAR(16) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description CLOB,
  status VARCHAR(32) NOT NULL DEFAULT 'NEW',
  owner VARCHAR(64),
  next_action VARCHAR(255),
  source_id VARCHAR(64) NOT NULL DEFAULT 'admin-ticket',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_human_intelligence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  link_id VARCHAR(64) NOT NULL,
  content CLOB NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  collector VARCHAR(64) NOT NULL,
  event_time VARCHAR(64),
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.7000,
  entitlement VARCHAR(32) NOT NULL DEFAULT 'FREE',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  reviewer VARCHAR(64),
  review_notes VARCHAR(512),
  source_id VARCHAR(64) NOT NULL DEFAULT 'human-intel',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_knowledge_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  link_id VARCHAR(64) NOT NULL DEFAULT 'general',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  draft_version_id BIGINT,
  review_version_id BIGINT,
  published_version_id BIGINT,
  source_id VARCHAR(64) NOT NULL DEFAULT 'admin-knowledge',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_knowledge_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL,
  version_number INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(1024),
  content CLOB NOT NULL,
  source_url VARCHAR(1024),
  review_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  author VARCHAR(64) NOT NULL,
  reviewer VARCHAR(64),
  review_notes VARCHAR(512),
  change_notes VARCHAR(512),
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8500,
  created_by_action VARCHAR(64) NOT NULL DEFAULT 'SAVE_DRAFT',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_knowledge_publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL,
  version_id BIGINT NOT NULL,
  action VARCHAR(32) NOT NULL,
  actor VARCHAR(64) NOT NULL,
  notes VARCHAR(512),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_collection_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  interval_minutes INT NOT NULL DEFAULT 30,
  max_retries INT NOT NULL DEFAULT 1,
  failure_threshold INT NOT NULL DEFAULT 3,
  cooldown_minutes INT NOT NULL DEFAULT 30,
  circuit_state VARCHAR(32) NOT NULL DEFAULT 'CLOSED',
  failure_count INT NOT NULL DEFAULT 0,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'general',
  link_id VARCHAR(64) NOT NULL DEFAULT 'collection',
  source_id VARCHAR(64) NOT NULL DEFAULT 'admin-collector',
  payload_json CLOB,
  compliance_notes CLOB,
  proxy_config CLOB,
  next_run_time TIMESTAMP,
  last_run_time TIMESTAMP,
  last_status VARCHAR(32) NOT NULL DEFAULT 'IDLE',
  last_error VARCHAR(1024),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_collection_keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_config_id BIGINT NOT NULL,
  keyword VARCHAR(255) NOT NULL,
  match_mode VARCHAR(32) NOT NULL DEFAULT 'INCLUDE',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  notes VARCHAR(512),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_collection_job_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  source_config_id BIGINT NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  trigger_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
  records_collected INT NOT NULL DEFAULT 0,
  records_filtered INT NOT NULL DEFAULT 0,
  records_persisted INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1024),
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finish_time TIMESTAMP
);

CREATE TABLE admin_risk_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description CLOB,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  threshold_value DECIMAL(8,4),
  scope_json CLOB,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  change_mode VARCHAR(16) NOT NULL DEFAULT 'IMMEDIATE',
  version INT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE report_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  report_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'READY',
  self_check_status VARCHAR(32) NOT NULL DEFAULT 'PASSED',
  sources_json CLOB NOT NULL,
  source_id VARCHAR(64) NOT NULL DEFAULT 'report',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE collection_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  queue_depth INT NOT NULL DEFAULT 0,
  retry_count INT NOT NULL DEFAULT 0,
  circuit_state VARCHAR(32) NOT NULL DEFAULT 'CLOSED',
  source_id VARCHAR(64) NOT NULL DEFAULT 'collector',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dead_letter_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT,
  reason VARCHAR(64) NOT NULL,
  error_message VARCHAR(1024) NOT NULL,
  payload_json CLOB,
  source_id VARCHAR(64) NOT NULL DEFAULT 'collector',
  weight DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  region_id VARCHAR(64) NOT NULL DEFAULT 'global',
  industry_id VARCHAR(64) NOT NULL DEFAULT 'global',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  source_url VARCHAR(1024),
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8500,
  link_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL DEFAULT 0.8500,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE raw_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  url VARCHAR(1024),
  confidence DECIMAL(8,4) NOT NULL,
  link_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL,
  industry_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL,
  metadata_json CLOB,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password_hash, role, phone_encrypted, identity_encrypted, membership_level, consultation_preferences, region_id, industry_id)
VALUES
  ('admin', 'password', 'SUPER_ADMIN', '13812345678', '110101199003071234', 'INTERNAL', 'operations', 'cn-default', 'general'),
  ('operator', 'password', 'OPERATOR', '13912345678', '110101199003071235', 'INTERNAL', 'review,alerts', 'cn-default', 'general'),
  ('user', 'password', 'USER', '13712345678', '110101199003071236', 'FREE', 'cashflow', 'cn-default', 'general'),
  ('seed_paid', 'password', 'USER', '13612345678', '110101199003071237', 'SEED_PAID', 'cashflow,inventory', 'cn-default', 'general');

INSERT INTO knowledge_items (title, content, source_url, confidence, link_id, region_id, industry_id, source_id, weight)
VALUES
  ('Test restaurant cash-flow baseline', 'Track客单价、翻台率、食材损耗率、平台佣金、租金占比和回款周期。', 'seed://v1/restaurant-cashflow', 0.9, 'sales-payment', 'cn-default', 'general', 'seed-baseline', 1.0),
  ('Test inventory risk baseline', '关注库存周转天数、滞销占比和上游账期变化对现金流的共同影响。', 'seed://v1/inventory-risk', 0.85, 'warehouse', 'cn-default', 'general', 'seed-baseline', 0.85);

INSERT INTO review_work_orders (target_type, target_id, reason, status, source_id, region_id, industry_id)
VALUES ('paid_intelligence', 1, 'SUSPICIOUS_CONFLICT', 'PENDING_REVIEW', 'paid-seed', 'cn-default', 'general');

INSERT INTO alert_events (alert_level, component, message, status, owner)
VALUES ('P2', 'collector', 'Collector fallback path requires gray-release drill.', 'OPEN', 'operator');

INSERT INTO audit_logs (actor, action, target_type, target_id, result)
VALUES ('operator', 'V2_M0_SCOPE_LOCK', 'milestone', 'v2', 'APPROVED');

CREATE TABLE sla_data_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start TIMESTAMP NOT NULL,
  window_end TIMESTAMP NOT NULL,
  total_requests INT NOT NULL DEFAULT 0,
  error_requests INT NOT NULL DEFAULT 0,
  latency_p50_ms DOUBLE,
  latency_p95_ms DOUBLE,
  latency_p99_ms DOUBLE,
  uptime_flag TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO alert_events (alert_level, component, message, status, owner)
VALUES ('P1', 'collector', 'Crawler success rate dropped below review threshold.', 'OPEN', 'operator');

INSERT INTO intelligence
  (title, content, url, status, confidence, link_id, region_id, industry_id, source_id, weight, content_hash)
VALUES
  ('Regional cash-flow pressure signal', 'Multiple local operators report longer account receivable cycles and higher rent pressure.', 'seed://admin/intelligence/cashflow', 'PENDING', 0.6200, 'sales-payment', 'cn-default', 'general', 'seed-admin', 0.6200, 'admin-seed-cashflow');

INSERT INTO admin_intelligence_reviews
  (intelligence_id, review_status, reason, evidence_json, region_id, industry_id)
VALUES (1, 'PENDING', 'Needs source and severity review', '[]', 'cn-default', 'general');

INSERT INTO admin_tickets
  (ticket_type, severity, target_type, target_id, title, description, status, owner, next_action, region_id, industry_id)
VALUES ('conflict', 'P1', 'intelligence', 1, 'Review old/new intelligence conflict', 'A newly collected local signal may conflict with an older baseline rule.', 'NEW', 'operator', 'Confirm whether this is short-term fluctuation or permanent rule change.', 'cn-default', 'general');

INSERT INTO admin_human_intelligence
  (city, industry_id, link_id, content, source_type, collector, event_time, confidence, entitlement, status, region_id)
VALUES ('Shanghai', 'general', 'sales-payment', 'Local store operators report increased supplier prepayment pressure this month.', 'local_visit', 'operator', '2026-07', 0.7200, 'PAID', 'PENDING_REVIEW', 'cn-default');

INSERT INTO admin_knowledge_nodes
  (id, title, slug, industry_id, region_id, link_id, status, published_version_id, source_id, weight)
VALUES (1, 'Store rent pressure playbook', 'store-rent-pressure-playbook', 'general', 'cn-default', 'sales-payment', 'PUBLISHED', 1, 'admin-knowledge', 1.0000);

INSERT INTO admin_knowledge_versions
  (id, node_id, version_number, title, summary, content, source_url, review_status, author, reviewer, review_notes, change_notes, confidence, created_by_action)
VALUES
  (1, 1, 1, 'Store rent pressure playbook', 'Baseline guidance for evaluating rising rent pressure against cash-flow tolerance.', 'Track rent-to-revenue ratio, landlord payment cadence, and whether temporary promotions are masking structural cost pressure.', 'seed://admin/knowledge/rent-pressure', 'APPROVED', 'system', 'operator', 'Seed approved', 'Bootstrap baseline', 0.8800, 'SEED');

INSERT INTO admin_knowledge_publications (node_id, version_id, action, actor, notes)
VALUES (1, 1, 'PUBLISH', 'system', 'Bootstrap publication');

ALTER TABLE admin_knowledge_nodes ALTER COLUMN id RESTART WITH 2;
ALTER TABLE admin_knowledge_versions ALTER COLUMN id RESTART WITH 2;

INSERT INTO admin_collection_sources
  (id, name, source_type, status, interval_minutes, max_retries, failure_threshold, cooldown_minutes, circuit_state, failure_count, region_id, industry_id, link_id, source_id, payload_json, next_run_time, last_status)
VALUES
  (1, 'Shanghai rent pressure page', 'PUBLIC_PAGE', 'ENABLED', 60, 1, 3, 30, 'CLOSED', 0, 'cn-default', 'general', 'sales-payment', 'admin-collector-public', '{"url":"https://example.com/shanghai-rent","html":"<html><title>Shanghai Rent Pressure</title><body>Landlords in Shanghai request shorter concession periods and faster payment cycles.</body></html>"}', CURRENT_TIMESTAMP, 'IDLE'),
  (2, 'Supplier prepayment mock API', 'MOCK_API', 'ENABLED', 120, 1, 3, 30, 'CLOSED', 0, 'cn-default', 'general', 'supply-chain', 'admin-collector-mock', '{"items":[{"title":"Supplier prepayment pressure","content":"Several suppliers now request larger advance payments.","url":"https://example.com/mock/prepayment","confidence":0.82,"weight":0.82,"industry_id":"general","region_id":"cn-default","link_id":"supply-chain"}]}', CURRENT_TIMESTAMP, 'IDLE');

ALTER TABLE admin_collection_sources ALTER COLUMN id RESTART WITH 3;

INSERT INTO admin_collection_keywords (source_config_id, keyword, match_mode, status, notes)
VALUES
  (1, 'rent', 'INCLUDE', 'ACTIVE', 'Track rent pressure signals'),
  (1, 'rumor', 'EXCLUDE', 'ACTIVE', 'Filter rumor-style content'),
  (2, 'prepayment', 'INCLUDE', 'ACTIVE', 'Focus on supplier prepayment signals');

INSERT INTO knowledge_items (title, content, source_url, confidence, link_id, region_id, industry_id, source_id, weight)
VALUES ('Store rent pressure playbook', 'Track rent-to-revenue ratio, landlord payment cadence, and whether temporary promotions are masking structural cost pressure.', 'seed://admin/knowledge/rent-pressure', 0.8800, 'sales-payment', 'cn-default', 'general', 'admin-node-1', 0.8800);

INSERT INTO audit_logs (actor, action, target_type, target_id, result)
VALUES ('system', 'ADMIN_V3_BOOTSTRAP', 'admin', 'seed', 'SUCCESS');

CREATE TABLE question_pools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  industry_id VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL DEFAULT 'cn-default',
  agent_mode VARCHAR(32) NOT NULL,
  question_key VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  question_text VARCHAR(512) NOT NULL,
  top_level_score DECIMAL(8,4) NOT NULL DEFAULT 0.5000,
  usage_count BIGINT NOT NULL DEFAULT 0,
  rating_avg DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  rating_count BIGINT NOT NULL DEFAULT 0,
  last_used_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
  source_type VARCHAR(32) NOT NULL DEFAULT 'seed',
  source_ref VARCHAR(128) NOT NULL DEFAULT '',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_question_pools_scope UNIQUE (industry_id, region_id, agent_mode, question_key)
);

INSERT INTO question_pools
  (industry_id, region_id, agent_mode, question_key, category, question_text, top_level_score, source_type, source_ref)
SELECT 'general', 'cn-default', 'LEARNING', 'raw-materials-next', 'node',
       '鍏堜簡瑙ｅ師鏉愭枡鎴愭湰缁撴瀯鍜岄噰璐懆鏈?, 0.92, 'seed', 'raw-materials'
WHERE NOT EXISTS (
  SELECT 1 FROM question_pools
  WHERE industry_id = 'general' AND region_id = 'cn-default'
    AND agent_mode = 'LEARNING' AND question_key = 'raw-materials-next'
);

INSERT INTO question_pools
  (industry_id, region_id, agent_mode, question_key, category, question_text, top_level_score, source_type, source_ref)
SELECT 'general', 'cn-default', 'DIAGNOSIS', 'baseline-industry', 'profile',
       '鍏堢‘璁や綘灞炰簬鍝釜琛屼笟锛屼互鍙婃槸绾夸笂杩樻槸绾夸笅涓氬姟', 0.95, 'seed', 'diagnosis-profile'
WHERE NOT EXISTS (
  SELECT 1 FROM question_pools
  WHERE industry_id = 'general' AND region_id = 'cn-default'
    AND agent_mode = 'DIAGNOSIS' AND question_key = 'baseline-industry'
);

INSERT INTO question_pools
  (industry_id, region_id, agent_mode, question_key, category, question_text, top_level_score, source_type, source_ref)
SELECT 'general', 'cn-default', 'DIAGNOSIS', 'baseline-scale', 'profile',
       '澶ф鐨勯棬搴椼€佷粨搴撳拰鍥㈤槦瑙勬ā鏄灏?, 0.93, 'seed', 'diagnosis-profile'
WHERE NOT EXISTS (
  SELECT 1 FROM question_pools
  WHERE industry_id = 'general' AND region_id = 'cn-default'
    AND agent_mode = 'DIAGNOSIS' AND question_key = 'baseline-scale'
);

INSERT INTO admin_risk_rules
  (rule_type, name, description, enabled, threshold_value, scope_json, risk_level, change_mode)
VALUES
  ('rumor_detection', 'Rumor keyword filter', 'Detect and flag content matching rumor patterns.', TRUE, 0.75, '{"industries":["all"],"regions":["all"]}', 'HIGH', 'IMMEDIATE'),
  ('conflict_judgment', 'New/old conflict detection', 'Flag intelligence that contradicts existing approved records.', TRUE, 0.60, '{"industries":["all"],"regions":["all"]}', 'MEDIUM', 'GRAY'),
  ('gray_content', 'Gray content sensitivity', 'Suppress borderline content from public APIs.', FALSE, 0.50, '{"industries":["general"],"regions":["cn-default"]}', 'MEDIUM', 'IMMEDIATE'),
  ('ai_self_check', 'AI output self-check threshold', 'Minimum confidence for AI-generated answers to pass self-check.', TRUE, 0.80, '{"industries":["all"],"regions":["all"]}', 'HIGH', 'IMMEDIATE'),
  ('api_abuse', 'API rate-limit protection', 'Detect and throttle abusive API request patterns.', TRUE, 0.90, '{"industries":["all"],"regions":["all"]}', 'CRITICAL', 'IMMEDIATE'),
  ('paid_protection', 'Paid content watermark', 'Ensure paid intelligence is not served to free-tier users.', TRUE, 1.00, '{"industries":["all"],"regions":["all"]}', 'CRITICAL', 'IMMEDIATE');
