CREATE TABLE sla_data_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start TIMESTAMP NOT NULL,
  window_end TIMESTAMP NOT NULL,
  total_requests INT NOT NULL DEFAULT 0,
  error_requests INT NOT NULL DEFAULT 0,
  latency_p50_ms DOUBLE,
  latency_p95_ms DOUBLE,
  latency_p99_ms DOUBLE,
  uptime_flag TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO alert_events (alert_level, component, message, status, owner)
VALUES ('P1', 'collector', 'Crawler success rate dropped below review threshold.', 'OPEN', 'operator');

INSERT INTO intelligence
  (title, content, url, status, confidence, link_id, region_id, industry_id, source_id, weight, content_hash)
VALUES
  ('Regional cash-flow pressure signal', 'Multiple local operators report longer account receivable cycles and higher rent pressure.', 'seed://admin/intelligence/cashflow', 'PENDING', 0.6200, 'sales-payment', 'cn-default', 'general', 'seed-admin', 0.6200, 'admin-seed-cashflow');

INSERT INTO admin_intelligence_reviews
  (intelligence_id, review_status, reason, evidence_json, region_id, industry_id)
VALUES (1, 'PENDING', 'Needs source and severity review', '[]', 'cn-default', 'general');

INSERT INTO admin_tickets
  (ticket_type, severity, target_type, target_id, title, description, status, owner, next_action, region_id, industry_id)
VALUES ('conflict', 'P1', 'intelligence', 1, 'Review old/new intelligence conflict', 'A newly collected local signal may conflict with an older baseline rule.', 'NEW', 'operator', 'Confirm whether this is short-term fluctuation or permanent rule change.', 'cn-default', 'general');

INSERT INTO admin_human_intelligence
  (city, industry_id, link_id, content, source_type, collector, event_time, confidence, entitlement, status, region_id)
VALUES ('Shanghai', 'general', 'sales-payment', 'Local store operators report increased supplier prepayment pressure this month.', 'local_visit', 'operator', '2026-07', 0.7200, 'PAID', 'PENDING_REVIEW', 'cn-default');

INSERT INTO admin_knowledge_nodes
  (id, title, slug, industry_id, region_id, link_id, status, published_version_id, source_id, weight)
VALUES (1, 'Store rent pressure playbook', 'store-rent-pressure-playbook', 'general', 'cn-default', 'sales-payment', 'PUBLISHED', 1, 'admin-knowledge', 1.0000);

INSERT INTO admin_knowledge_versions
  (id, node_id, version_number, title, summary, content, source_url, review_status, author, reviewer, review_notes, change_notes, confidence, created_by_action)
VALUES
  (1, 1, 1, 'Store rent pressure playbook', 'Baseline guidance for evaluating rising rent pressure against cash-flow tolerance.', 'Track rent-to-revenue ratio, landlord payment cadence, and whether temporary promotions are masking structural cost pressure.', 'seed://admin/knowledge/rent-pressure', 'APPROVED', 'system', 'operator', 'Seed approved', 'Bootstrap baseline', 0.8800, 'SEED');

INSERT INTO admin_knowledge_publications (node_id, version_id, action, actor, notes)
VALUES (1, 1, 'PUBLISH', 'system', 'Bootstrap publication');

INSERT INTO admin_collection_sources
  (id, name, source_type, status, interval_minutes, max_retries, failure_threshold, cooldown_minutes, circuit_state, failure_count, region_id, industry_id, link_id, source_id, payload_json, next_run_time, last_status)
VALUES
  (1, 'Shanghai rent pressure page', 'PUBLIC_PAGE', 'ENABLED', 60, 1, 3, 30, 'CLOSED', 0, 'cn-default', 'general', 'sales-payment', 'admin-collector-public', '{"url":"https://example.com/shanghai-rent","html":"<html><title>Shanghai Rent Pressure</title><body>Landlords in Shanghai request shorter concession periods and faster payment cycles.</body></html>"}', CURRENT_TIMESTAMP, 'IDLE'),
  (2, 'Supplier prepayment mock API', 'MOCK_API', 'ENABLED', 120, 1, 3, 30, 'CLOSED', 0, 'cn-default', 'general', 'supply-chain', 'admin-collector-mock', '{"items":[{"title":"Supplier prepayment pressure","content":"Several suppliers now request larger advance payments.","url":"https://example.com/mock/prepayment","confidence":0.82,"weight":0.82,"industry_id":"general","region_id":"cn-default","link_id":"supply-chain"}]}', CURRENT_TIMESTAMP, 'IDLE');

INSERT INTO admin_collection_keywords (source_config_id, keyword, match_mode, status, notes)
VALUES
  (1, 'rent', 'INCLUDE', 'ACTIVE', 'Track rent pressure signals'),
  (1, 'rumor', 'EXCLUDE', 'ACTIVE', 'Filter rumor-style content'),
  (2, 'prepayment', 'INCLUDE', 'ACTIVE', 'Focus on supplier prepayment signals');

INSERT INTO knowledge_items (title, content, source_url, confidence, link_id, region_id, industry_id, source_id, weight)
VALUES ('Store rent pressure playbook', 'Track rent-to-revenue ratio, landlord payment cadence, and whether temporary promotions are masking structural cost pressure.', 'seed://admin/knowledge/rent-pressure', 0.8800, 'sales-payment', 'cn-default', 'general', 'admin-node-1', 0.8800);

INSERT INTO audit_logs (actor, action, target_type, target_id, result)
VALUES ('system', 'ADMIN_V3_BOOTSTRAP', 'admin', 'seed', 'SUCCESS');

INSERT INTO admin_risk_rules
  (rule_type, name, description, enabled, threshold_value, scope_json, risk_level, change_mode)
VALUES
  ('rumor_detection', 'Rumor keyword filter', 'Detect and flag content matching rumor patterns.', TRUE, 0.75, '{"industries":["all"],"regions":["all"]}', 'HIGH', 'IMMEDIATE'),
  ('conflict_judgment', 'New/old conflict detection', 'Flag intelligence that contradicts existing approved records.', TRUE, 0.60, '{"industries":["all"],"regions":["all"]}', 'MEDIUM', 'GRAY'),
  ('gray_content', 'Gray content sensitivity', 'Suppress borderline content from public APIs.', FALSE, 0.50, '{"industries":["general"],"regions":["cn-default"]}', 'MEDIUM', 'IMMEDIATE'),
  ('ai_self_check', 'AI output self-check threshold', 'Minimum confidence for AI-generated answers to pass self-check.', TRUE, 0.80, '{"industries":["all"],"regions":["all"]}', 'HIGH', 'IMMEDIATE'),
  ('api_abuse', 'API rate-limit protection', 'Detect and throttle abusive API request patterns.', TRUE, 0.90, '{"industries":["all"],"regions":["all"]}', 'CRITICAL', 'IMMEDIATE'),
  ('paid_protection', 'Paid content watermark', 'Ensure paid intelligence is not served to free-tier users.', TRUE, 1.00, '{"industries":["all"],"regions":["all"]}', 'CRITICAL', 'IMMEDIATE');
