package com.bizsage.api.messages;

import jakarta.annotation.PostConstruct;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.Locale;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Service
public class ConversationSchemaMigration {
  private final JdbcTemplate jdbcTemplate;

  public ConversationSchemaMigration(JdbcTemplate jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
  }

  @PostConstruct
  void migrate() {
    ensureConversationSummariesTable();
    ensureMessagesColumn("message_type", "varchar(32) not null default 'CHAT'");
    ensureMessagesColumn("sources_json", "longtext");
    ensureMessagesColumn("confidence", "varchar(16)");
    ensureMessagesColumn("timeliness", "varchar(255)");
    ensureMessagesColumn("self_check_status", "varchar(32)");
    ensureMessagesColumn("is_active_context", "boolean not null default true");
    ensureMessagesColumn("summary_group_id", "bigint");
    ensureMessagesColumn("region_id", "varchar(64) not null default 'cn-default'");
    ensureMessagesColumn("industry_id", "varchar(64) not null default 'general'");
    ensureMessagesColumn("source_id", "varchar(64) not null default 'conversation'");
    ensureMessagesColumn("weight", "decimal(8,4) not null default 1.0000");
    ensureMessagesColumn("update_time", "timestamp not null default current_timestamp");
  }

  private void ensureConversationSummariesTable() {
    if (tableExists("conversation_summaries")) {
      return;
    }
    jdbcTemplate.execute("""
        create table conversation_summaries (
          id bigint generated by default as identity primary key,
          conversation_id bigint not null,
          summary_text clob not null,
          covered_message_start_id bigint not null,
          covered_message_end_id bigint not null,
          summary_version int not null default 1,
          active boolean not null default true,
          source_id varchar(64) not null default 'summary',
          weight decimal(8,4) not null default 1.0000,
          create_time timestamp not null default current_timestamp,
          update_time timestamp not null default current_timestamp
        )
        """);
  }

  private void ensureMessagesColumn(String columnName, String columnDefinition) {
    if (!tableExists("messages") || columnExists("messages", columnName)) {
      return;
    }
    jdbcTemplate.execute("alter table messages add column " + columnName + " " + columnDefinition);
  }

  private boolean tableExists(String tableName) {
    return jdbcTemplate.execute((java.sql.Connection connection) -> {
      DatabaseMetaData metadata = connection.getMetaData();
      try (ResultSet tables = metadata.getTables(connection.getCatalog(), null, null, new String[] {"TABLE"})) {
        while (tables.next()) {
          String current = tables.getString("TABLE_NAME");
          if (tableName.equalsIgnoreCase(normalize(current))) {
            return true;
          }
        }
        return false;
      }
    });
  }

  private boolean columnExists(String tableName, String columnName) {
    return jdbcTemplate.execute((java.sql.Connection connection) -> {
      DatabaseMetaData metadata = connection.getMetaData();
      try (ResultSet columns = metadata.getColumns(connection.getCatalog(), null, null, null)) {
        while (columns.next()) {
          String currentTable = columns.getString("TABLE_NAME");
          String currentColumn = columns.getString("COLUMN_NAME");
          if (tableName.equalsIgnoreCase(normalize(currentTable))
              && columnName.equalsIgnoreCase(normalize(currentColumn))) {
            return true;
          }
        }
        return false;
      }
    });
  }

  private String normalize(String identifier) {
    if (identifier == null) {
      return "";
    }
    return identifier.toLowerCase(Locale.ROOT);
  }
}
