package com.bizsage.api.ops;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class AlertRuleEngineTest {

  @Test
  void circuitBreakerEvaluationUsesCurrentAdminCollectionSourcesTable() {
    JdbcTemplate jdbc = new JdbcTemplate(new DriverManagerDataSource(
        "jdbc:h2:mem:alert_rule_engine;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
        "sa",
        ""));
    jdbc.execute("""
        create table admin_collection_sources (
          id bigint primary key,
          name varchar(255) not null,
          circuit_state varchar(32) not null
        )
        """);
    jdbc.execute("""
        create table alert_events (
          id bigint generated by default as identity primary key,
          alert_level varchar(16) not null,
          component varchar(64) not null,
          message varchar(512) not null,
          status varchar(32) not null,
          region_id varchar(64) not null,
          industry_id varchar(64) not null,
          create_time timestamp default current_timestamp
        )
        """);
    jdbc.update("""
        insert into admin_collection_sources (id, name, circuit_state)
        values (7, 'Supplier prepayment mock API', 'OPEN')
        """);

    OpsQueryMapper mapper = new OpsQueryMapper() {
      @Override
      public List<Map<String, Object>> listAlerts() {
        throw new UnsupportedOperationException();
      }

      @Override
      public List<Map<String, Object>> listReviewWorkOrders() {
        throw new UnsupportedOperationException();
      }

      @Override
      public List<Map<String, Object>> listAuditLogs() {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countAuditLogsByResult(String result, Instant since, Instant until) {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countRecentApiErrors() {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countRecentApiCalls() {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countRecentCollectionRuns() {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countRecentFailedCollectionRuns() {
        throw new UnsupportedOperationException();
      }

      @Override
      public List<Map<String, Object>> listOpenCircuits() {
        return jdbc.queryForList("select id, name from admin_collection_sources where circuit_state = 'OPEN'");
      }

      @Override
      public Integer countActiveDbConnections() {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countStaleKnowledgeItems(int days) {
        throw new UnsupportedOperationException();
      }

      @Override
      public Integer countOpenAlertsForComponent(String component) {
        return jdbc.queryForObject(
            "select count(*) from alert_events where component = ? and status not in ('CLOSED') limit 1",
            Integer.class,
            component);
      }

      @Override
      public int insertAlert(String level, String component, String message) {
        return jdbc.update(
            "insert into alert_events (alert_level, component, message, status, region_id, industry_id) values (?, ?, ?, 'OPEN', 'global', 'global')",
            level,
            component,
            message);
      }
    };

    new AlertRuleEngine(mapper, 0.05, 0.20, 30).evaluateCircuitBreakerState();

    String message = jdbc.queryForObject("""
        select message from alert_events
         where component = 'circuit-breaker'
        """, String.class);
    assertThat(message).contains("#7").contains("Supplier prepayment mock API");
  }
}
